# -*- coding: utf-8 -*-
"""Final_Project_VISDAT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kMqBYVKntKukGP_antDwPP13GqhxeFY7

## Final Project
### MK Visualisasi Data

### Preparing Library
"""

# import library

import pandas as pd
from bokeh.io import curdoc, output_file, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.models import CategoricalColorMapper
from bokeh.palettes import Spectral6
from bokeh.layouts import widgetbox, row, gridplot
from bokeh.models import Select

"""### Preparing Dataset"""

# import dataset

data = pd.read_csv("stock_market.csv")
data['Date'] = pd.to_datetime(data['Date'])
data = data.rename(columns={'Adj Close': 'Adj_Close'})
# data.set_index('Date', inplace=True)
data.head()

"""## Level 1"""

# Make a list of the unique values from the Name column: idx_list
idx_list = data.Name.unique().tolist()

# Make a color mapper: color_mapper
color_mapper = CategoricalColorMapper(factors=idx_list, palette=Spectral6)

# Make the ColumnDataSource: source
source = ColumnDataSource(data={
    'x'       : data.Date,
    'y'       : data.Adj_Close,
    'Volume' : data.Volume,
    'Day_Perc_Change' : data.Day_Perc_Change,
    'Name'  : data.Name,
})

# Format the tooltip
tooltips = [
            ('Index Name','@Name'),
            ('Adj Close', '@y{00000.0}'),
           ]

# Create the figure: plot
plot = figure(title='Index Adj Close Value', x_axis_type='datetime', x_axis_label='Date', y_axis_label='Adj Close',
           plot_height=400, plot_width=700)

# Add the HoverTool to the figure
plot.add_tools(HoverTool(tooltips=tooltips))

# Add a circle glyph to the figure p
plot.circle(x='x', y='y', source=source, fill_alpha=0.8,
           color=dict(field='Name', transform=color_mapper), legend='Name')

# Move the legend to the upper left corner
plot.legend.location = 'top_left'

# Visualize
show(plot)
